include: "rules/common.smk"

localrules: count_nucl_kmers, generate_snakemake_dag

####### Target rules #######
rule all:
    input:
        "results/snakemake_dag.png",
        expand(
            "results/all_{nucl_kmer_length}mer_counts.csv",
            nucl_kmer_length=config['parameters']["nucl_kmer_length"]
        ),
        expand(
            "results/feature_engineering/kmer_counts/{nucl_kmer_length}mers/{genome_name}_{nucl_kmer_length}mers.txt", 
            genome_name=genome_names,
            nucl_kmer_length=config["parameters"]["nucl_kmer_length"]
        ),
        # "data/merged_data.csv",
        # "results/modeling/xgboost_gridsearch.pkl"


####### Meta rules #######
rule generate_snakemake_dag:
    input:
    output:
        "results/snakemake_dag.png"
    log:
        err = "logs/snakemake_dag.err",
        out = "logs/snakemake_dag.out"
    shell:
        "snakemake --rulegraph | dot -Tpng > {output}"

rule clean_all:
    shell:
        """
        rm -rf logs/*
        rm -rf .snakemake/log/*
        """

####### Modules #######
include: "rules/feature_engineering.smk"
# include: "rules/modeling.smk"
