phenotype:
  # csv file containing genome names and any corresponding phenotypes
  # the first column should be named genome and the values here
  # should match the file names of the fasta files the pipeline is being
  # run on 
  phenotype_file: scratch/phenotypes.csv

  # Column from the above file that the prediction pipeline should be run on
  target_column: group

  # Every other value will be considered a feature


directories:
  # genome_directory: Directory containing the genome files of interest
  # The pipeline will look for files ending in fa, fna, fasta, and fastq inside this directory
  # genome_directory: /project/fsepru/paul.villanueva/repos/snakemake-genome-assembly-practice/output/genomes

  # Full directory
  genome_directory: data/genomes

  # Smaller testing directory
  # genome_directory: data/short_genomes
  
  # Where intermediate files are stored.
  working_dir: working

  # Will be a subfolder of the working directory
  kmc_temp_dir: working/kmc_temp

  gene_target_dir: data/gene_targets

parameters:
  nucl_kmer_length: 15
  aa_kmer_lengths: [3, 4, 5, 10, 11]


