# Where to download the SRA files 
# sra_download_directory

# Where intermediate kmc files should g
# kmc_temp_files

# Length of nucleotide k-mers
# nucl_kmer_length

# Length of AA k-mers
# aa_kmer_length

# File containing SRAs to download
# sra_list

# How many SRAs of the total list to download?
# If left blank, will download all of them.
# num_sras_to_download