phenotype:
  # csv file containing genome names and any corresponding phenotypes
  # the first column should be named genome and the values here
  # should match the file names of the fasta files the pipeline is being
  # run on 
  phenotype_file: scratch/phenotypes.csv

  # Column from the above file that the prediction pipeline should be run on
  target_column: group

  # Every other value will be considered a feature


directories:
  # Directory containing the genome files of interest
  # The pipeline will look for files ending in fa, fna, fasta, and fastq inside this directory
  genome_directory: /90daydata/fsepru/paul.villanueva/practice_genomes
  # Where intermediate kmc files are stored.
  kmc_temp_dir: data/kmc_temp

# Length of nucleotide k-mers
# nucl_kmer_length

# Length of AA k-mers
# aa_kmer_length
