data_prep:
  # Directory containing the genome files of interest
  genome_directory: scratch/genomes
  # Where intermediate kmc files should g
  kmc_temp_dir: data/kmc_temp

# Length of nucleotide k-mers
# nucl_kmer_length

# Length of AA k-mers
# aa_kmer_length
